{{ if and .Values.ingress.enabled .Values.ingress.contour.enabled }}
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: {{ .Values.controller.name }}-httpproxy
spec:
  virtualhost:
    fqdn: {{ .Values.ingress.contour.fqdn }}
  routes:
  - services:
    - name: {{ .Values.controller.name }}
      port: 8080
{{ end }}
